service: my-lambda-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev
  environment:
    DYNAMODB_TABLE_NAME: tasks
    S3_BUCKET_NAME: task-attachments-task-management

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-offline
