name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm ci
      
    - name: Build
      run: npm run build
      
    - name: Package Lambda
      run: |
        mkdir -p dist-lambda
        cp -r dist/* dist-lambda/
        cp package.json dist-lambda/
        cd dist-lambda
        npm install --production
        npm ci --production
        zip -r ../function.zip .
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to Lambda
      run: aws lambda update-function-code --function-name task-management-api --zip-file fileb://function.zip